# For encrytion and decryption
OTP_SALT = 'aSquare_otp_salt'

METHOD_NOT_ALLOWED = "Method not allowed"
GET_METHOD_NOT_ALLOWED = "GET method not allowed"
UNAUTHORIZED = "Your are not authorized to access this resource"
ACCESS_DENIED = "Access denied"
ACCOUNT_NOT_ACTIVATED = "Your account is not activated yet"
NOT_FOUND = "Not found"
BAD_REQUEST = "Bad request"
INTERNAL_SERVER_ERROR = "Internal server error"
PHONE_NUMBER_REQUIRED = "Phone number required"
EMAIL_REQUIRED = "Email required"
PASSWORD_REQUIRED = "Password required"
INVALID_PHONE_NUMBER = "Invalid phone number"
INVALID_EMAIL = "Invalid email"
INVALID_PAN_NUMBER = "Invalid pan number"
PROVIDE_ALL_REQUIRED_FIELDS = "Provide all required fields"
LOGIN_SUCCESSFUL = "Login successful"
LOGIN_FAILED = "Login failed"
PROVIDE_VALID_CREDENTIALS = "Provide valid credentials"
EMAIL_ALREADY_EXISTS = "Email already exists"
PHONE_NUMBER_ALREADY_EXISTS = "Phone number already exists"
SIGNUP_SUCCESSFUL = "Signup successful"
SIGNUP_FAILED = "Signup failed"
SIGNUP_FIRST_TO_VERIFY_OTP = "You have not signup yet. Please signup first to verify your email."
OTP_SENT_SUCCESSFULLY = "OTP sent successfully"
OTP_SENT_FAILED = "OTP sending failed"
OTP_CODE_REQUIRED = "OTP code required"
INVALID_OTP_CODE = "OTP code is invalid"
OTP_CODE_EXPIRED = "OTP code was expired"
OTP_MUST_BE_IN_NUMBER = "OTP must be in number"
OTP_VERIFICATION_SUCCESS = "OTP verification successful"
OTP_VERIFICATION_FAILED = "OTP verification failed"
USER_NOT_FOUND = "User not found"
NO_CHANGES_MADE = "No changes made"

# Category Section
CATEGORY_DATA_REQUIRED = "Category data required"
CATEGORY_NAME_REQUIRED = "Category name required"
CATEGORY_CREATED_SUCCESSFULLY = "Category created successfully"
CATEGORY_CREATED_FAILED = "Category creation failed"
CATEGORY_UPDATED_SUCCESSFULLY = "Category updated successfully"
CATEGORY_UPDATED_FAILED = "Category updation failed"
CATEGORY_NOT_FOUND = "Category not found"
STORE_CATEGORY_NOT_FOUND = "Store category not found"
STORE_CATEGORY_RETRIEVED = "Store category retrieve successfully"
STORE_CATEGORIES_RETRIEVED = "Store categories retrieve successfully"
STORE_SUB_CATEGORIES_RETRIEVED = "Store sub categories retrieve successfully"
STORE_CATEGORY_CREATED = "Store category created successfully"
STORE_CATEGORY_UPDATED = "Store category updated successfully"
STORE_CATEGORY_DELETED = "Store category deleted successfully"
STORE_CATEGORIES_NOT_FOUND = "Store categories not found"
STORE_SUB_CATEGORY_NOT_FOUND = "Store sub category not found"
CATEGORY_ID_NOT_FOUND = "Category id not found"
STORE_CATEGORY_ID_REQUIRED = "Store category id required"
CATEGORY_RETRIEVED = "Category retrieve successfully"
CATEGORY_NAME_ALREADY_EXISTS = "Category name already exists"

# Store Section
STORE_NOT_FOUND = "Store not found"
STORE_ALREADY_EXISTS = "Store already exists"
STORE_NAME_REQUIRED = "Store name is required"
STORE_PHONE_REQUIRED = "Store phone is required"
STORE_EMAIL_REQUIRED = "Store email is required"
STORE_ADDRESS_REQUIRED = "Store address is required"
STORE_OWNER_DATA_REQUIRED = "Store owner's data is required"
STORE_PAN_NUMBER_REQUIRED = "Store PAN number is required"
STORE_CATEGORY_REQUIRED = "Store category is required"
STORE_ID_REQUIRED = "Store id is required"

ADDRESS_LINE_1_REQUIRED = "Store address line 1 is required"
ADDRESS_CITY_REQUIRED = "City is required"
ADDRESS_STATE_REQUIRED = "State is required"
ADDRESS_COUNTRY_REQUIRED = "Country is required"
ADDRESS_PIN_CODE_REQUIRED = "Pincode is required"
STORE_ADDRESS_INVALID = "Store address is invalid"

STORE_ADDED_SUCCESSFULLY = "Store added successfully"
STORE_UPDATED_SUCCESSFULLY = "Store updated successfully"
STORE_ADD_FAILED = "Failed to add store"
STORE_UPDATE_FAILED = "Store update failed. Please change the data and try again!!"
STORE_STAFF_NOT_FOUND = "Store staff not found"
STORE_STAFF_RETRIEVED = "Store staff retrieved successfully"
STORE_STAFF_CREATED = "Store staff created successfully"
STORE_STAFF_UPDATED = "Store staff updated successfully"
STAFF_ID_REQUIRED = "Staff id is required"
STAFF_STORE_NOT_FOUND = "You are not associated with any store"
NOT_STAFF_OF_STORE = "You are not associated with any store"
UNAUTHORIZED_TO_ACCESS_OR_MODIFY_ANOTHER_STORE_RESOURCE = "You are not authorized to access or modify another store resource"

STORE_LIST_RETRIEVED = "Store list retrieved"
STORE_RETRIEVED = "Store retrieved"
FAILED_TO_RETRIEVE_STORE = "Failed to retrieve store"
FAILED_TO_RETRIEVE_STORE_LIST = "Failed to retrieve store list"

# Product Section
PRODUCT_CATEGORY_NOT_FOUND = "Product category not found"
PRODUCT_CATEGORIES_RETRIEVED = "Product categories retrieved successfully"
PRODUCT_CATEGORY_CREATED = "Product category created successfully"
PRODUCT_CATEGORY_UPDATED = "Product category updated successfully"
PRODUCT_CATEGORY_DELETED = "Product category deleted successfully"
PRODUCT_CATEGORY_ID_REQUIRED = "Product category id is required"
PRODUCT_NOT_FOUND = "Product not found"

PRODUCT_NOT_APPROVED = "Product is not approved yet"
BASE_PRODUCTS_RETRIEVED = "Base products retrieved successfully"
BASE_PRODUCT_NOT_FOUND = "Base product not found"
BASE_PRODUCT_RETRIEVED = "Base product retrieved successfully"
PRODUCT_IS_NOT_BASE_PRODUCT = "Product is not base product"

PRODUCT_DATA_REQUIRED = "Product data is required"
PRODUCT_NAME_REQUIRED = "Product name is required"
PRODUCT_SELLING_PRICE_REQUIRED = "Product selling price is required"
PRODUCT_MRP_REQUIRED = "Product MRP is required"
PRODUCT_CATEGORY_REQUIRED = "Product category is required"
PRODUCT_BRAND_REQUIRED = "Product brand is required"
PRODUCT_SKU_REQUIRED = "Product sku is required"
PRODUCT_PARENT_REQUIRED = "Product parent is required"
PRODUCT_VARIATION_ATTRIBUTE_VALUE_REQUIRED = "Product variation attribute's value is required"
PRODUCT_QUANTITY_REQUIRED = "Product quantity is required"
PRODUCT_STORE_REQUIRED = "Product store is required"
PRODUCT_ALREADY_EXISTS = "Product already exists"
PRODUCT_ID_REQUIRED = "Product id is required"
PRODUCT_ADDED_SUCCESSFULLY = "Product added successfully"
PRODUCT_UPDATED_SUCCESSFULLY = "Product updated successfully"
PRODUCT_ADD_FAILED = "Failed to add product"
PRODUCT_UPDATE_FAILED = "Product update failed. Please change the data and try again!!"
PRODUCT_LIST_RETRIEVED = "Product list retrieved"
PRODUCT_RETRIEVED = "Product retrieved"
FAILED_TO_RETRIEVE_PRODUCT = "Failed to retrieve product"
FAILED_TO_RETRIEVE_PRODUCT_LIST = "Failed to retrieve product list"

ATTRIBUTE_LIST_RETRIEVED = "Attribute list retrieved"
ATTRIBUTE_RETRIEVED = "Attribute retrieved"
FAILED_TO_RETRIEVE_ATTRIBUTE = "Failed to retrieve attribute"
FAILED_TO_RETRIEVE_ATTRIBUTE_LIST = "Failed to retrieve attribute list"
CATEGORY_ID_REQUIRED = "Category id is required"
ATTRIBUTE_DATA_REQUIRED = "Attribute data is required"
ATTRIBUTE_NAME_REQUIRED = "Attribute name is required"
ATTRIBUTE_ALREADY_EXISTS = "Attribute already exists"
ATTRIBUTE_ADDED_SUCCESSFULLY = "Attribute added successfully"
ATTRIBUTE_UPDATED_SUCCESSFULLY = "Attribute updated successfully"
ATTRIBUTE_ADD_FAILED = "Failed to add attribute"
ATTRIBUTE_UPDATE_FAILED = "Attribute update failed. Please change the data and try again!!"
ATTRIBUTE_ID_REQUIRED = "Attribute id is required"
ATTRIBUTE_DOES_NOT_EXIST = "Attribute does not exist"

VARIATION_ATTRIBUTE_RETRIEVED = "Variation attribute retrieved"
VARIATION_ATTRIBUTE_NOT_FOUND = "Variation attribute not found"
VARIATION_ATTRIBUTE_LIST_RETRIEVED = "Variation attribute list retrieved"
VARIATION_ATTRIBUTE_ADDED_SUCCESSFULLY = "Variation attribute added successfully"
VARIATION_ATTRIBUTE_UPDATED_SUCCESSFULLY = "Variation attribute updated successfully"
VARIATION_ATTRIBUTE_ADD_FAILED = "Failed to add variation attribute"
VARIATION_ATTRIBUTE_UPDATE_FAILED = "Variation attribute update failed. Please change the data and try again!!"
VARIATION_ATTRIBUTE_ID_REQUIRED = "Variation attribute id is required"
VARIATION_ATTRIBUTE_DATA_REQUIRED = "Variation attribute data is required"
VARIATION_ATTRIBUTE_NAME_REQUIRED = "Variation attribute name is required"
VARIATION_ATTRIBUTE_ALREADY_EXISTS = "Variation attribute already exists"

VARIATION_ATTRIBUTE_VALUE_LIST_RETRIEVED = "Variation attribute value list retrieved"
VARIATION_ATTRIBUTE_VALUE_RETRIEVED = "Variation attribute value retrieved"
VARIATION_ATTRIBUTE_VALUE_NOT_FOUND = "Variation attribute value not found"
VARIATION_ATTRIBUTE_VALUE_ADDED_SUCCESSFULLY = "Variation attribute value added successfully"
VARIATION_ATTRIBUTE_VALUE_UPDATED_SUCCESSFULLY = "Variation attribute value updated successfully"
VARIATION_ATTRIBUTE_VALUE_ADD_FAILED = "Failed to add variation attribute value"
VARIATION_ATTRIBUTE_VALUE_UPDATE_FAILED = "Variation attribute value update failed. Please change the data and try again!!"
VARIATION_ATTRIBUTE_VALUE_ID_REQUIRED = "Variation attribute value id is required"
VARIATION_ATTRIBUTE_VALUE_DATA_REQUIRED = "Variation attribute value data is required"
VARIATION_ATTRIBUTE_VALUE_REQUIRED = "Variation attribute value is required"
VARIATION_ATTRIBUTE_VALUE_ALREADY_EXISTS = "Variation attribute value already exists"

PRODUCT_ATTRIBUTE_LIST_RETRIEVED = "Product attribute list retrieved"
PRODUCT_ATTRIBUTE_RETRIEVED = "Product attribute retrieved"
FAILED_TO_RETRIEVE_PRODUCT_ATTRIBUTE = "Failed to retrieve product attribute"
FAILED_TO_RETRIEVE_PRODUCT_ATTRIBUTE_LIST = "Failed to retrieve product attribute list"
PRODUCT_ATTRIBUTE_ID_REQUIRED = "Product attribute id is required"

PRODUCT_ATTRIBUTE_ALREADY_EXISTS = "Product attribute already exists"
PRODUCT_ATTRIBUTE_DATA_REQUIRED = "Product attribute data is required"
PRODUCT_ATTRIBUTE_VALUE_REQUIRED = "Product attribute value is required"
PRODUCT_ATTRIBUTE_ADDED_SUCCESSFULLY = "Product attribute added successfully"
PRODUCT_ATTRIBUTE_UPDATED_SUCCESSFULLY = "Product attribute updated successfully"
PRODUCT_ATTRIBUTE_ADD_FAILED = "Failed to add product attribute"
PRODUCT_ATTRIBUTE_UPDATE_FAILED = "Product attribute update failed. Please change the data and try again!!"
PRODUCT_ATTRIBUTE_NOT_FOUND = "Product attribute not found"

BRAND_LIST_RETRIEVED = "Brand list retrieved"
BRAND_RETRIEVED = "Brand retrieved"
FAILED_TO_RETRIEVE_BRAND = "Failed to retrieve brand"
FAILED_TO_RETRIEVE_BRAND_LIST = "Failed to retrieve brand list"
BRAND_ID_REQUIRED = "Brand id is required"
BRAND_ADDED_SUCCESSFULLY = "Brand added successfully"
BRAND_UPDATED_SUCCESSFULLY = "Brand updated successfully"
BRAND_ADD_FAILED = "Failed to add brand"
BRAND_UPDATE_FAILED = "Brand update failed. Please change the data and try again!!"
BRAND_DATA_REQUIRED = "Brand data is required"
BRAND_NAME_REQUIRED = "Brand name is required"
BRAND_ALREADY_EXISTS = "Brand already exists"
BRAND_DOES_NOT_EXIST = "Brand does not exist"

PRODUCT_PRICE_LIST_RETRIEVED = "Product price list retrieved"
PRODUCT_PRICE_RETRIEVED = "Product price retrieved"
FAILED_TO_RETRIEVE_PRODUCT_PRICE = "Failed to retrieve product price"
PRODUCT_PRICE_DATA_REQUIRED = "Product price data is required"
PRODUCT_PRICE_ADDED_SUCCESSFULLY = "Product price added successfully"
PRODUCT_PRICE_UPDATED_SUCCESSFULLY = "Product price updated successfully"
PRODUCT_PRICE_ADD_FAILED = "Failed to add product price"
PRODUCT_PRICE_UPDATE_FAILED = "Product price update failed. Please change the data and try again!!"
PRODUCT_PRICE_NOT_FOUND = "Product price not found"

PRODUCT_STOCK_DATA_REQUIRED = "Product stock data is required"
PRODUCT_STOCK_ADDED_SUCCESSFULLY = "Product stock added successfully"
PRODUCT_STOCK_UPDATED_SUCCESSFULLY = "Product stock updated successfully"
PRODUCT_STOCK_ADD_FAILED = "Failed to add product stock"
PRODUCT_STOCK_UPDATE_FAILED = "Product stock update failed. Please change the data and try again!!"
PRODUCT_STOCK_LIST_RETRIEVED = "Product stock list retrieved"
PRODUCT_STOCK_RETRIEVED = "Product stock retrieved"
FAILED_TO_RETRIEVE_PRODUCT_STOCK = "Failed to retrieve product stock"
PRODUCT_STOCK_NOT_FOUND = "Product stock not found"

PRODUCT_IMAGE_LIST_RETRIEVED = "Product image list retrieved"
PRODUCT_IMAGE_RETRIEVED = "Product image retrieved"
FAILED_TO_RETRIEVE_PRODUCT_IMAGE = "Failed to retrieve product image"
PRODUCT_IMAGE_DATA_REQUIRED = "Product image data is required"
PRODUCT_IMAGE_REQUIRED = "Product image is required"
PRODUCT_IMAGE_ADDED_SUCCESSFULLY = "Product image added successfully"
PRODUCT_IMAGE_UPDATED_SUCCESSFULLY = "Product image updated successfully"
PRODUCT_IMAGE_ADD_FAILED = "Failed to add product image"
PRODUCT_IMAGE_UPDATE_FAILED = "Product image update failed. Please change the data and try again!!"

QUERY_REQUIRED = "Query is required"

PRODUCT_REVIEW_DATA_REQUIRED = "Product review data is required"
PRODUCT_REVIEW_ADDED_SUCCESSFULLY = "Product review added successfully"
PRODUCT_REVIEW_UPDATED_SUCCESSFULLY = "Product review updated successfully"
PRODUCT_REVIEW_ADD_FAILED = "Failed to add product review"
PRODUCT_REVIEW_UPDATE_FAILED = "Product review update failed. Please change the data and try again!!"
PRODUCT_REVIEW_LIST_RETRIEVED = "Product review list retrieved"
PRODUCT_REVIEW_RETRIEVED = "Product review retrieved"
FAILED_TO_RETRIEVE_PRODUCT_REVIEW = "Failed to retrieve product review"
PRODUCT_REVIEW_NOT_FOUND = "Product review not found"
RATING_REQUIRED = "Rating is required"
COMMENT_REQUIRED = "Comment is required"
CUSTOMER_ID_REQUIRED = "Customer id is required"
REVIEW_ALREADY_ADDED = "Review already added"
